In [ ]:
#print(np.concatenate([arr1,arr2],axis = 1))#axis=0horizontally output of rows
# in axis 1 we are adding more columns to the array

# To create an ndarray, we can pass a list, tuple or any array-like object into the array() method,
# and it will be converted into an ndarray:


In [1]:
import numpy as np

a = np.array([20,30,40])
b = np.array([4])
print(a)
print(b)
print(a*b)

[20 30 40]
[4]
[ 80 120 160]


In [2]:
a = np.array([[20,30,10],[40,50,60]]) # in numpy the data type we store once willconvertall values to that dtype
print(a)

[[20 30 10]
 [40 50 60]]


In [3]:
l1 = [[20,30,40],[40,50,60]]
print(l1)

[[20, 30, 40], [40, 50, 60]]


In [4]:
# [50,60,70,80],[20,40,60,80]
arr = np.array([[10,20,30,40],[50,60,70,80],[20,40,60,80]])
print(np.shape(arr)) # how many rows and columns are there
print(np.size(arr)) # size shows altogether how many values are in each array 
print(np.ndim(arr)) # shows number of dimensions
print(arr.dtype)

(3, 4)
12
2
int32


# Inspecting an array

In [96]:
a = [[30,40,40],[40,30.8,10]] 
arr = np.array(a)
print(arr)
print(arr.shape) # rows, columns
print(len(arr)) # number of nested elements
print(np.size(arr)) # number of elements 
print(type(arr)) # data type of variable
print(arr.dtype) # datatype of array
print(arr.astype(int)) # conversion of datatype

[[30.  40.  40. ]
 [40.  30.8 10. ]]
(2, 3)
2
6
<class 'numpy.ndarray'>
float64
[[30 40 40]
 [40 30 10]]


# Performing Mathematical Calculations on arrays

In [6]:
arr1 = np.array([[30,40],[20,10]])
arr2 = np.array([[30,20],[10,20]])
print(arr1 + arr2)
print(np.add(arr1,arr2))

[[60 60]
 [30 30]]
[[60 60]
 [30 30]]


In [7]:
arr1 = np.array([[30,40],[20,10]])
arr2 = np.array([[30,20],[10,20]])
print(arr1-arr2)
print(np.subtract(arr1,arr2))

[[  0  20]
 [ 10 -10]]
[[  0  20]
 [ 10 -10]]


In [8]:
arr1 = np.array([[30,40],[20,10]])
arr2 = np.array([[30,20],[10,20]])
print(arr1*arr2)
print(np.multiply(arr1,arr2))

[[900 800]
 [200 200]]
[[900 800]
 [200 200]]


In [9]:
arr1 = np.array([[30,40],[20,10]])
arr2 = np.array([[30,20],[10,20]])
print(arr1/arr2)
print(np.divide(arr1,arr2))

[[1.  2. ]
 [2.  0.5]]
[[1.  2. ]
 [2.  0.5]]


In [10]:
arr1 = np.array([3,4,2,1])
arr2 = np.array([2])
print(np.power(arr1,arr2))

[ 9 16  4  1]


In [11]:
arr1 = np.array([9,16,4,1])
print(np.sqrt(arr1))

[3. 4. 2. 1.]


# Join And Split

In [12]:
a = [30,40,50]
b = [5,5,3]
print(a+b)

[30, 40, 50, 5, 5, 3]


In [13]:
#Concatenate
arr1 = np.array([[30,40],[50,10]])
arr2 = np.array([[5,5],[3,3]])
print(np.concatenate([arr1,arr2]))

[[30 40]
 [50 10]
 [ 5  5]
 [ 3  3]]


In [20]:
print(np.concatenate([arr1,arr2],axis = 1)) # axis=1 horizontally output of rows
# in axis 1 we are adding more columns to the array

[[30 40  5  5]
 [50 10  3  3]]


In [19]:
print(np.hstack([arr1,arr2])) # horizontal concatenation 

[[30 40  5  5]
 [50 10  3  3]]


In [21]:
print(np.vstack([arr1,arr2])) # vertical concatenation

[[30 40]
 [50 10]
 [ 5  5]
 [ 3  3]]


In [37]:
a = np.array([[20,40,30],[40,10,20]])
b = np.array_split(a,2)
print(b)

[array([[20, 40, 30]]), array([[40, 10, 20]])]


# Adding and Removing Elements in the Arrays..

In [45]:
a = np.array([[20,40],[60,80]]) 
print(np.append(a,[90,100]))      

[ 20  40  60  80  90 100]


In [50]:
print(np.insert(a,[1,2],[50], axis = 0))  # arr,index,value

[[20 40]
 [50 50]
 [60 80]
 [50 50]]


In [53]:
print(a)
print(np.delete(a,1, axis = 1))

[[20 40]
 [60 80]]
[[20]
 [60]]


In [55]:
ar = np.array([[7,8,4,12,9], [2,8,5,1,3]])
print(np.sort(ar))

[[ 4  7  8  9 12]
 [ 1  2  3  5  8]]


In [58]:
ar = np.array([3,4,1,7,8]) # search shows index of values
s = np.where(ar % 2 == 0)
print(s)

(array([1, 4], dtype=int64),)


In [60]:
ar = np.array([1,2,3,4,5]) # arrayshouldbe sorted to apply searchsortedfunction
ss = np.searchsorted(ar,5)
print(ss)

4


In [62]:
# filter 
ar = np.array([20,30,40,50]) # array should be equal to fa

fa = [True, False, False, False]

new = ar[fa]
print(new)

[20]


In [65]:
ar = np.array([2,3,4,5])

fa = ar%2 == 1
new = ar[fa]
print(new)

[3 5]


# Aggregating Functions

In [72]:
a = np.array([20,40,60,70])

print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.size(a))
print(np.mean(a))
print(np.cumsum(a))#itaddspreviousvaluewiththe nextvalue to printnextalue
print(np.cumprod(a))

190
20
70
4
47.5
[ 20  60 120 190]
[     20     800   48000 3360000]


In [89]:
a = [100,150,199,200,250,130]
b = [10,50,30,40,30,10]

price = np.array(a)
quantity = np.array(b)

print(price, "\n" ,quantity)
print()
c = np.cumprod([price,quantity], axis = 0)
print(c[1].sum())

[100 150 199 200 250 130] 
 [10 50 30 40 30 10]

31270


# Statistical Functions

In [95]:
import statistics as stats

baked_food = [200,150,150,130,200,220,170,188]

a = np.array(baked_food)
print(np.mean(baked_food)) # sum of al values/number of values
print(np.median(baked_food)) # central value after sorting
print(stats.mode(baked_food)) # it takes the first most ocurring value 
print(np.std(baked_food)) # std ** means variance
print(np.var(baked_food))

176.0
179.0
200
29.017236257093817
842.0
